# Generated by Django 4.2 on 2023-04-05 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Invalid name format', regex='[A-Z]{1}[a-z]*')])),
                ('last_name', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Invalid name format', regex='[A-Z]{1}[a-z]*')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
